### ISSUE TITLE
[Feature] Use of an external maplist

### ISSUE THREAD

**Issue by mavproductions** [oqyh/cs2-Auto-Rotate-Maps-GoldKingZ#1]
Hey @oqyh,

Wondering if you're able to have the plugin support other maplist.txt in different server directories. These maplists might have other formats where they can read real map names or plain workshop names `ie. surf_utopia_njv` vs `ds:surf_utopia_njv`.

Think this is possible? yay? nay?

Hope you've been well.

-maV.

**Comment by oqyh** [comment]
> Hey @oqyh,
> 
> Wondering if you're able to have the plugin support other maplist.txt in different server directories. These maplists might have other formats where they can read real map names or plain workshop names `ie. surf_utopia_njv` vs `ds:surf_utopia_njv`.
> 
> Think this is possible? yay? nay?
> 
> Hope you've been well.
> 
> -maV.

try 1.0.1

**Comment by mavproductions** [comment]
Wow! will do! Thank you so much - will let you know how it goes! Incredibly talented coder :)

**Comment by mavproductions** [comment]
> > Hey @oqyh,
> > Wondering if you're able to have the plugin support other maplist.txt in different server directories. These maplists might have other formats where they can read real map names or plain workshop names `ie. surf_utopia_njv` vs `ds:surf_utopia_njv`.
> > Think this is possible? yay? nay?
> > Hope you've been well.
> > -maV.
> 
> try 1.0.1
Hey oqyh,
Sorry to be a bother with this. Are you able to add support for this formatting: `aim_map_s2r:3070260370`? Basically just adding the addition of suffix support to the name. Sorry I know this is probably a tedious ask 😔

**Comment by mavproductions** [comment]
> > Hey @oqyh,
> > Wondering if you're able to have the plugin support other maplist.txt in different server directories. These maplists might have other formats where they can read real map names or plain workshop names `ie. surf_utopia_njv` vs `ds:surf_utopia_njv`.
> > Think this is possible? yay? nay?
> > Hope you've been well.
> > -maV.
> 
> try 1.0.1

Hey oqyh,
Sorry to be a bother with this. Are you able to add support for this formatting: aim_map_s2r:3070260370? Basically just adding the addition of suffix support to the name. Sorry I know this is probably a tedious ask 😔

**Comment by oqyh** [comment]
> Hey oqyh,
> Sorry to be a bother with this. Are you able to add support for this formatting: aim_map_s2r:3070260370? Basically just adding the addition of suffix support to the name. Sorry I know this is probably a tedious ask 😔

we can but we try to not make it complex just add names in txt i dont see it big deal

**Comment by mavproductions** [comment]
> > Hey oqyh,
> > Sorry to be a bother with this. Are you able to add support for this formatting: aim_map_s2r:3070260370? Basically just adding the addition of suffix support to the name. Sorry I know this is probably a tedious ask 😔
> 
> we can but we try to not make it complex just add names in txt i dont see it big deal

Unfortunately this is how [CS2-RockTheVote](https://github.com/abnerfs/cs2-rockthevote) manages workshop maps currently. That being said this RTV plugin pairs really nicely with other mods on my server.

**Comment by oqyh** [comment]
> 3070260370

still not big deal just replace it wwith host:3070260370

**Comment by mavproductions** [comment]
Oh I see, sorry.

With my setup, the file changes dynamically depending on what mode the server is on. It could be active duty, DM maps, surf, kz, etc.

So it's a file that is always changing basically, depending on the mode. So ideally your plugin would be able to read dynamically changing suffix formatted map names.

**Comment by oqyh** [comment]
> Oh I see, sorry.
> 
> With my setup, the file changes dynamically depending on what mode the server is on. It could be active duty, DM maps, surf, kz, etc.
> 
> So it's a file that is always changing basically, depending on the mode. So ideally your plugin would be able to read dynamically changing suffix formatted map names.

ok so you want me to fix/enchance cs2-rockthevote this not the plugin, you can ask the author for it 
but this plugin idea is Cycle maps depending on the number of players
